baseURL = 'https://www.kaishen.ca/'
languageCode = 'en-us'
theme = "hello-friend"
paginate = 5
summaryLength = 30

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 6
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "Kai Shen"
    subtitle = ""
    keywords = ""
    copyright = "Kai Shen &copy; 2023"
    menuMore = "More"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [params.logo]
    logoText = "Kai Shen"
    logoHomeLink = "/"
    [[menu.main]]
        identifier = "Projects"
        weight = 1
        name = "Projects"
        url = "/projects"
    [menu]
      [[menu.main]]
        identifier = "Teaching"
        weight = 2
        name = "Teaching"
        url = "/teaching"
      [[menu.main]]
        identifier = "Professional Services"
        weight = 3
        name = "Professional Services"
        url = "/professional_services"